name: Build and Publish Docker to dockerhub

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    # Runs a single command using the runners shell
    - name: Publish to Docker Hub
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: juicygoose/hacienda
        username: juicygoose
        password: ${{ secrets.DOCKER_PASSWORD }}
